School/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls')),
    path("patients/",include('Patient.urls')),
    path('accounts/',include('accounts.urls')),
    path('Doctors/',include('Doctors.urls')),
]

accounts/urls.py
from django.urls import path
from . import views 


app_name = 'accounts'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name="login"),
    path("Patient-signup/", views.Patient_register.as_view(), name="patientsignup"),
    path("Doctor-signup/", views.Doctor_register.as_view(), name="doctorsignup"),
    path("logout/", views.logout_view, name="logout")
]

landingpage/urls.py
from django.urls import path
from . import views 


app_name = 'landing'

urlpatterns = [
    path('',views.Index,name="index"),
    path('blog-list/',views.Blog,name="blog"),
]

landingpage/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from django.template.defaultfilters import slugify



class Blog(models.Model):
    title = models.CharField(max_length=550, blank=False)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, unique_for_date="created_at", blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to="posts/images/", null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    content = models.TextField()

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
    class Meta:
        ordering = ['-created_at']
    

landingpage/views.py
from django.shortcuts import render



def Index(request):
    context = {}
    return render(request,'landingpage/index.html',context)


def Blog(request):
    context = {}
    return render(request, 'landingpage/blog.html',context)

landingpage/templates/landingpage/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <!-- Mirrored from doccure-html.dreamguystech.com/cardiology/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 06 May 2021 12:43:14 GMT -->
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=0"
    />
    <title>Doccure-Cardiology</title>

    <!-- Favicons -->
    <link
      type="image/x-icon"
      href="{% static 'assets/img/favicon.png' %}"
      rel="icon"
    />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />

    <!-- Fontawesome CSS -->
    <link
      rel="stylesheet"
      href="{% static 'assets/plugins/fontawesome/css/fontawesome.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}"
    />

    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="assets/js/html5shiv.min.js"></script>
      <script src="assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Main Wrapper -->
    <div class="main-wrapper">
      <!-- Header -->
      <header class="header">
        <nav class="navbar navbar-expand-lg header-nav">
          <div class="navbar-header">
            <a id="mobile_btn" href="javascript:void(0);">
              <span class="bar-icon">
                <span></span>
                <span></span>
                <span></span>
              </span>
            </a>
            <a href="index-2.html" class="navbar-brand logo">
              <img
                src="{% static 'assets/img/logo.png' %}"
                class="img-fluid"
                alt="Logo"
              />
            </a>
          </div>
          <div class="main-menu-wrapper">
            <div class="menu-header">
              <a href="index-2.html" class="menu-logo">
                <img
                  src="{% static 'assets/img/logo.png' %}"
                  class="img-fluid"
                  alt="Logo"
                />
              </a>
              <a id="menu_close" class="menu-close" href="javascript:void(0);">
                <i class="fas fa-times"></i>
              </a>
            </div>
            <ul class="main-nav">
              <li class="active">
                <a href="{% url 'landing:index' %}">Home</a>
              </li>

              <li>
                <a href="{% url 'landing:blog' %}">Blog </a>
              </li>
              <li>
                <a href="{% url 'accounts:patientsignup' %}">Patient </a>
              </li>
              <li>
                <a href="{% url 'accounts:doctorsignup' %}">Doctor </a>
              </li>
              <li>
                <a href="admin/index.html" target="_blank">Admin</a>
              </li>
              <li class="login-link">
                <a href="{% url 'accounts:login' %}">Login / Signup</a>
              </li>
            </ul>
          </div>
          <ul class="nav header-navbar-rht">
            <li class="nav-item contact-item">
              <div class="header-contact-img">
                <i class="far fa-hospital"></i>
              </div>
              <div class="header-contact-detail">
                <p class="contact-header">Contact</p>
                <p class="contact-info-header">+1 315 369 5943</p>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link header-login" href="{% url 'accounts:login' %}"
                >login / Signup
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <!-- /Header -->
      {% block content %}{% endblock content %}

      <!-- Footer -->
      <footer class="footer">
        <!-- Footer Top -->
        <div class="footer-top">
          <div class="container-fluid">
            <div class="row">
              <div class="col-lg-3 col-md-6">
                <!-- Footer Widget -->
                <div class="footer-widget footer-about">
                  <div class="footer-logo">
                    <img
                      src="{% static 'assets/img/footer-logo.png' %}"
                      alt="logo"
                    />
                  </div>
                  <div class="footer-about-content">
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore et dolore magna
                      aliqua.
                    </p>
                    <div class="social-icon">
                      <ul>
                        <li>
                          <a href="#" target="_blank"
                            ><i class="fab fa-facebook-f"></i>
                          </a>
                        </li>
                        <li>
                          <a href="#" target="_blank"
                            ><i class="fab fa-twitter"></i>
                          </a>
                        </li>
                        <li>
                          <a href="#" target="_blank"
                            ><i class="fab fa-linkedin-in"></i
                          ></a>
                        </li>
                        <li>
                          <a href="#" target="_blank"
                            ><i class="fab fa-instagram"></i
                          ></a>
                        </li>
                        <li>
                          <a href="#" target="_blank"
                            ><i class="fab fa-dribbble"></i>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
                <!-- /Footer Widget -->
              </div>

              <div class="col-lg-3 col-md-6">
                <!-- Footer Widget -->
                <div class="footer-widget footer-menu">
                  <h2 class="footer-title">For Patients</h2>
                  <ul>
                    <li><a href="search.html">Search for Doctors</a></li>
                    <li><a href="login.html">Login</a></li>
                    <li><a href="register.html">Register</a></li>
                    <li><a href="booking.html">Booking</a></li>
                    <li>
                      <a href="patient-dashboard.html">Patient Dashboard</a>
                    </li>
                  </ul>
                </div>
                <!-- /Footer Widget -->
              </div>

              <div class="col-lg-3 col-md-6">
                <!-- Footer Widget -->
                <div class="footer-widget footer-menu">
                  <h2 class="footer-title">For Doctors</h2>
                  <ul>
                    <li><a href="appointments.html">Appointments</a></li>
                    <li><a href="chat.html">Chat</a></li>
                    <li><a href="login.html">Login</a></li>
                    <li><a href="doctor-register.html">Register</a></li>
                    <li>
                      <a href="doctor-dashboard.html">Doctor Dashboard</a>
                    </li>
                  </ul>
                </div>
                <!-- /Footer Widget -->
              </div>

              <div class="col-lg-3 col-md-6">
                <!-- Footer Widget -->
                <div class="footer-widget footer-contact">
                  <h2 class="footer-title">Contact Us</h2>
                  <div class="footer-contact-info">
                    <div class="footer-address">
                      <span><i class="fas fa-map-marker-alt"></i></span>
                      <p>
                        3556 Beech Street, San Francisco,<br />
                        California, CA 94108
                      </p>
                    </div>
                    <p>
                      <i class="fas fa-mobile-alt"></i>
                      +1 315 369 5943
                    </p>
                    <p class="mb-0">
                      <i class="fas fa-envelope"></i>
                      doccure@example.com
                    </p>
                  </div>
                </div>
                <!-- /Footer Widget -->
              </div>
            </div>
          </div>
        </div>
        <!-- /Footer Top -->

        <!-- Footer Bottom -->
        <div class="footer-bottom">
          <div class="container-fluid">
            <!-- Copyright -->
            <div class="copyright">
              <div class="row">
                <div class="col-md-6 col-lg-6">
                  <div class="copyright-text">
                    <p class="mb-0">
                      &copy; 2020 Doccure. All rights reserved.
                    </p>
                  </div>
                </div>
                <div class="col-md-6 col-lg-6">
                  <!-- Copyright Menu -->
                  <div class="copyright-menu">
                    <ul class="policy-menu">
                      <li>
                        <a href="term-condition.html">Terms and Conditions</a>
                      </li>
                      <li><a href="privacy-policy.html">Policy</a></li>
                    </ul>
                  </div>
                  <!-- /Copyright Menu -->
                </div>
              </div>
            </div>
            <!-- /Copyright -->
          </div>
        </div>
        <!-- /Footer Bottom -->
      </footer>
      <!-- /Footer -->
    </div>
    <!-- jQuery -->
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JS -->
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

    <!-- Slick JS -->
    <script src="{% static 'assets/js/slick.js' %}"></script>

    <!-- Custom JS -->
    <script src="{% static 'assets/js/script.js' %}"></script>
  </body>

  <!-- Mirrored from doccure-html.dreamguystech.com/cardiology/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 06 May 2021 12:46:47 GMT -->
</html>

landingpage/templates/landingpage/blog.html
{% extends 'landingpage/base.html' %} {% load static %} {% block content %}

<!-- Breadcrumb -->
<div class="breadcrumb-bar">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-md-12 col-12">
        <nav aria-label="breadcrumb" class="page-breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Blog</li>
          </ol>
        </nav>
        <h2 class="breadcrumb-title">Blog List</h2>
      </div>
    </div>
  </div>
</div>
<!-- /Breadcrumb -->

<!-- Page Content -->
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-12">
        <!-- Blog Post -->
        <div class="blog">
          <div class="blog-image">
            <a href="blog-details.html"
              ><img
                class="img-fluid"
                src="{% static 'assets/img/blog/blog-01.jpg' %}"
                alt="Post Image"
            /></a>
          </div>
          <h3 class="blog-title">
            <a href="blog-details.html"
              >Doccure – Making your clinic painless visit?</a
            >
          </h3>
          <div class="blog-info clearfix">
            <div class="post-left">
              <ul>
                <li>
                  <div class="post-author">
                    <a href="doctor-profile.html"
                      ><img
                        src="{% static 'assets/img/doctors/doctor-thumb-01.jpg' %}"
                        alt="Post Author"
                      />
                      <span>Dr. Ruby Perrin</span></a
                    >
                  </div>
                </li>
                <li><i class="far fa-clock"></i>4 Dec 2019</li>
                <li><i class="far fa-comments"></i>12 Comments</li>
                <li><i class="fa fa-tags"></i>Health Tips</li>
              </ul>
            </div>
          </div>
          <div class="blog-content">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco sit
              laboris ullamco laborisut aliquip ex ea commodo consequat. Ut enim
              ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquip ex ea commodo consequat.
            </p>
            <a href="blog-details.html" class="read-more">Read More</a>
          </div>
        </div>
        <!-- /Blog Post -->

        <!-- Blog Pagination -->
        <div class="row">
          <div class="col-md-12">
            <div class="blog-pagination">
              <nav>
                <ul class="pagination justify-content-center">
                  <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1"
                      ><i class="fas fa-angle-double-left"></i
                    ></a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">1</a>
                  </li>
                  <li class="page-item active">
                    <a class="page-link" href="#"
                      >2 <span class="sr-only">(current)</span></a
                    >
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#">3</a>
                  </li>
                  <li class="page-item">
                    <a class="page-link" href="#"
                      ><i class="fas fa-angle-double-right"></i
                    ></a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
        <!-- /Blog Pagination -->
      </div>

      <!-- Blog Sidebar -->
      <div class="col-lg-4 col-md-12 sidebar-right theiaStickySidebar">
        <!-- Search -->
        <div class="card search-widget">
          <div class="card-body">
            <form class="search-form">
              <div class="input-group">
                <input
                  type="text"
                  placeholder="Search..."
                  class="form-control"
                />
                <div class="input-group-append">
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- /Search -->

        <!-- Latest Posts -->
        <div class="card post-widget">
          <div class="card-header">
            <h4 class="card-title">Latest Posts</h4>
          </div>
          <div class="card-body">
            <ul class="latest-posts">
              <li>
                <div class="post-thumb">
                  <a href="blog-details.html">
                    <img
                      class="img-fluid"
                      src="{% static 'assets/img/blog/blog-thumb-01.jpg' %}"
                      alt=""
                    />
                  </a>
                </div>
                <div class="post-info">
                  <h4>
                    <a href="blog-details.html"
                      >Doccure – Making your clinic painless visit?</a
                    >
                  </h4>
                  <p>4 Dec 2019</p>
                </div>
              </li>
              <li>
                <div class="post-thumb">
                  <a href="blog-details.html">
                    <img
                      class="img-fluid"
                      src="{% static 'assets/img/blog/blog-thumb-02.jpg' %}"
                      alt=""
                    />
                  </a>
                </div>
                <div class="post-info">
                  <h4>
                    <a href="blog-details.html"
                      >What are the benefits of Online Doctor Booking?</a
                    >
                  </h4>
                  <p>3 Dec 2019</p>
                </div>
              </li>
              <li>
                <div class="post-thumb">
                  <a href="blog-details.html">
                    <img
                      class="img-fluid"
                      src="{% static 'assets/img/blog/blog-thumb-03.jpg' %}"
                      alt=""
                    />
                  </a>
                </div>
                <div class="post-info">
                  <h4>
                    <a href="blog-details.html"
                      >Benefits of consulting with an Online Doctor</a
                    >
                  </h4>
                  <p>3 Dec 2019</p>
                </div>
              </li>
              <li>
                <div class="post-thumb">
                  <a href="blog-details.html">
                    <img
                      class="img-fluid"
                      src="{% static 'assets/img/blog/blog-thumb-04.jpg' %}"
                      alt=""
                    />
                  </a>
                </div>
                <div class="post-info">
                  <h4>
                    <a href="blog-details.html"
                      >5 Great reasons to use an Online Doctor</a
                    >
                  </h4>
                  <p>2 Dec 2019</p>
                </div>
              </li>
              <li>
                <div class="post-thumb">
                  <a href="blog-details.html">
                    <img
                      class="img-fluid"
                      src="{% static 'assets/img/blog/blog-thumb-05.jpg' %}"
                      alt=""
                    />
                  </a>
                </div>
                <div class="post-info">
                  <h4>
                    <a href="blog-details.html"
                      >Online Doctor Appointment Scheduling</a
                    >
                  </h4>
                  <p>1 Dec 2019</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
        <!-- /Latest Posts -->
      </div>
      <!-- /Blog Sidebar -->
    </div>
  </div>
</div>
<!-- /Page Content -->

{% endblock content %}