Doctors/urls.py
from django.urls import  path
from . import views 

app_name="doctors"

urlpatterns = [
    path('Doctor-dashboard/',views.Dashboard,name='Doctordashboard'),
    path('Doctor-appointments/',views.Appointments,name='DoctorAppointments'),
    path('Doctor-patients/',views.patients,name='DoctorPatients'),
    path('Doctor-profile/',views.DoctorProfile,name='DoctorProfile'),
    path('Doctor-password/',views.ChangePaword,name="passwordchange"),
]

Patient/urls.py
from django.urls import path,include
from . import views

app_name="patient"

urlpatterns = [
    path("Patient/", views.PatientDashboard, name="PatientDashboard"),
    path("Profile/", views.Profile, name="profile"),
    path("favourites/", views.Favourites, name="favourites"),
    path("search-doctor/", views.SearchDoctor, name="search"),
    path("book-doctor/", views.Booking, name="booking"),
    path("book-sucess/", views.BookingSuccess, name="bookingsucess"),
    path("book-payments/", views.Payments, name="Payments"),
    path("enter-info/", views.EnterUserinfo, name="enterinfo"),
]

School/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls')),
    path("patients/",include('Patient.urls')),
    path('accounts/',include('accounts.urls')),
    path('Doctors/',include('Doctors.urls')),
]

accounts/urls.py
from django.urls import path
from . import views 


app_name = 'accounts'

urlpatterns = [
    path('login/',views.LoginView.as_view(),name="login"),
    path("Patient-signup/", views.Patient_register.as_view(), name="patientsignup"),
    path("Doctor-signup/", views.Doctor_register.as_view(), name="doctorsignup"),
    path("logout/", views.logout_view, name="logout")
]

Patient/models.py
from django.db import models
from django.conf import settings
from Doctors.models import Doctorprofile
from django.template.defaultfilters import slugify



class Patientsprofile(models.Model):
    patientname =models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='pateintprofile')
    age = models.PositiveSmallIntegerField(null=True,blank=True)

    def __str__(self):
        return self.patientname
    


class Appointments(models.Model):
    patient =models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='Appoitments')
    Doctor = models.ForeignKey(Doctorprofile, on_delete=models.CASCADE, related_name='doctor')
    appointment_date = models.DateField(auto_now_add=False)
    booking = models.DateField(auto_now_add=True)
    price = models.CharField(max_length=50)
    flowup = models.DateField(auto_now_add=False,null=True,blank=True)
    status = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True, unique_for_date="appointment_date")
    accepted = models.BooleanField(default=False)



    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'Appointment of {self.patient}'

    class Meta:
        ordering = ['-appointment_date']

    

Patient/forms.py
from django.forms import fields
from accounts.models import PatientProfile
from django import forms


class PatientProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PatientProfileForm, self).__init__(*args, **kwargs)
        self.fields['Address'].widget.attrs = {'class': 'form-control','placeholder':'Enter your address'}
        self.fields['Mobile'].widget.attrs = {'class': 'form-control','placeholder':'Enter your Mobile number'}
        self.fields['Date_Of_Birth'].widget.attrs = {'class': 'form-control','placeholder':'Enter your Date of birth'}
        self.fields['Blood_Group'].widget.attrs = {'class': 'form-control','placeholder':'Enter your address'}
        self.fields['city'].widget.attrs = {'class': 'form-control','placeholder':'Enter your city'}
        self.fields['District'].widget.attrs = {'class': 'form-control','placeholder':'Enter your district'}
        self.fields['Country'].widget.attrs = {'class': 'form-control','placeholder':'Enter your country'}
        self.fields['profile_image'].widget.attrs = {'class': 'upload'}
        self.fields['Gender'].widget.attrs = {'class': 'form-control select','required':True}

    class Meta:
        model = PatientProfile  
        fields = ['user','Address','Mobile','profile_image','Date_Of_Birth','Blood_Group','city','District','Country','Gender',]

Patient/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import * 


@login_required(login_url='/accounts/login/')
def PatientDashboard(request):
    context = { }
    return render (request, 'Patient/dashboard.html',context)

@login_required(login_url='/accounts/login/')
def Profile(request):
    context = { }
    return render (request, 'Patient/profile.html',context)


@login_required(login_url='/accounts/login/')
def Favourites(request):
    context = {}
    return render(request,'Patient/favourites.html',context)


@login_required(login_url='/accounts/login/')
def SearchDoctor(request):
    context = {}
    return render(request,'Patient/search.html',context)



@login_required(login_url='/accounts/login/')
def Booking(request):
    context = {}
    return render(request,'Patient/booking.html',context)


@login_required(login_url='/accounts/login/')
def BookingSuccess(request):
    context = {}
    return render(request,'Patient/success.html',context)



@login_required(login_url='/accounts/login/')
def Payments(request):
    context = {}
    return render(request,'Patient/payments.html',context)

@login_required(login_url='/accounts/login/')
def EnterUserinfo(request):
    if request.method == 'POST':
        form = PatientProfileForm(request.POST or None)
    else:
        form = PatientProfileForm()

        
    context = {'form':form,}
    return render(request,'Patient/info.html',context)

Patient/templates/Patient/favourites.html
{% extends 'Patient/base.html' %} {% load static %} {% block content %}

<!-- Breadcrumb -->
<div class="breadcrumb-bar">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-md-12 col-12">
        <nav aria-label="breadcrumb" class="page-breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index-2.html">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">
              Favourites
            </li>
          </ol>
        </nav>
        <h2 class="breadcrumb-title">Favourites</h2>
      </div>
    </div>
  </div>
</div>
<!-- /Breadcrumb -->

<!-- Page Content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
     <!-- Profile Sidebar -->
      <div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">
        <div class="profile-sidebar">
          <div class="widget-profile pro-widget-content">
            <div class="profile-info-widget">
              <a href="#" class="booking-doc-img">
                <img
                  src="{% static 'assets/img/patients/patient.jpg' %}"
                  alt="User Image"
                />
              </a>
              <div class="profile-det-info">
                <h3>George Anderson</h3>
                <div class="patient-details">
                  <h5>
                    <i class="fas fa-birthday-cake"></i> 24 Jul 1983, 38 years
                  </h5>
                  <h5 class="mb-0">
                    <i class="fas fa-map-marker-alt"></i> Newyork, USA
                  </h5>
                </div>
              </div>
            </div>
          </div>
          <div class="dashboard-widget">
            <nav class="dashboard-menu">
              <ul>
                <li class="active">
                  <a href="{% url 'patient:PatientDashboard' %}">
                    <i class="fas fa-columns"></i>
                    <span>Dashboard</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'patient:favourites' %}">
                    <i class="fas fa-bookmark"></i>
                    <span>Favourites</span>
                  </a>
                </li>
                {% comment %}
                <li>
                  <a href="chat.html">
                    <i class="fas fa-comments"></i>
                    <span>Message</span>
                    <small class="unread-msg">23</small>
                  </a>
                </li>
                {% endcomment %}
                <li>
                  <a href="{% url 'patient:profile' %}">
                    <i class="fas fa-user-cog"></i>
                    <span>Search Doctor</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'patient:profile' %}">
                    <i class="fas fa-user-cog"></i>
                    <span>Profile Settings</span>
                  </a>
                </li>
                <li>
                  <a href="change-password.html">
                    <i class="fas fa-lock"></i>
                    <span>Change Password</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'accounts:logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
      <!-- / Profile Sidebar -->
      <div class="col-md-7 col-lg-8 col-xl-9">
        <div class="row row-grid">
          <div class="col-md-6 col-lg-4 col-xl-3">
            <div class="profile-widget">
              <div class="doc-img">
                <a href="doctor-profile.html">
                  <img
                    class="img-fluid"
                    alt="User Image"
                    src="{% static 'assets/img/doctors/doctor-01.jpg' %}"
                  />
                </a>
                <a href="javascript:void(0)" class="fav-btn">
                  <i class="far fa-bookmark"></i>
                </a>
              </div>
              <div class="pro-content">
                <h3 class="title">
                  <a href="doctor-profile.html">Dr. Ruby Perrin</a>
                  <i class="fas fa-check-circle verified"></i>
                </h3>
                <p class="speciality">
                  MDS - Periodontology and Oral Implantology, BDS
                </p>
                <div class="rating">
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <span class="d-inline-block average-rating">(17)</span>
                </div>
                <ul class="available-info">
                  <li><i class="fas fa-map-marker-alt"></i> Florida, USA</li>
                  <li><i class="far fa-clock"></i> Available on Fri, 22 Mar</li>
                  <li>
                    <i class="far fa-money-bill-alt"></i> $300 - $1000
                    <i
                      class="fas fa-info-circle"
                      data-toggle="tooltip"
                      title="Lorem Ipsum"
                    ></i>
                  </li>
                </ul>
                <div class="row row-sm">
                  <div class="col-6">
                    <a href="doctor-profile.html" class="btn view-btn"
                      >View Profile</a
                    >
                  </div>
                  <div class="col-6">
                    <a href="booking.html" class="btn book-btn">Book Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 col-xl-3">
            <div class="profile-widget">
              <div class="doc-img">
                <a href="doctor-profile.html">
                  <img
                    class="img-fluid"
                    alt="User Image"
                    src="{% static 'assets/img/doctors/doctor-02.jpg' %}"
                  />
                </a>
                <a href="javascript:void(0)" class="fav-btn">
                  <i class="far fa-bookmark"></i>
                </a>
              </div>
              <div class="pro-content">
                <h3 class="title">
                  <a href="doctor-profile.html">Dr. Fred Ortego</a>
                  <i class="fas fa-check-circle verified"></i>
                </h3>
                <p class="speciality">
                  BDS, MDS - Oral & Maxillofacial Surgery
                </p>
                <div class="rating">
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star"></i>
                  <span class="d-inline-block average-rating">(35)</span>
                </div>
                <ul class="available-info">
                  <li><i class="fas fa-map-marker-alt"></i> Newyork, USA</li>
                  <li><i class="far fa-clock"></i> Available on Fri, 22 Mar</li>
                  <li>
                    <i class="far fa-money-bill-alt"></i> $50 - $300
                    <i
                      class="fas fa-info-circle"
                      data-toggle="tooltip"
                      title="Lorem Ipsum"
                    ></i>
                  </li>
                </ul>
                <div class="row row-sm">
                  <div class="col-6">
                    <a href="doctor-profile.html" class="btn view-btn"
                      >View Profile</a
                    >
                  </div>
                  <div class="col-6">
                    <a href="booking.html" class="btn book-btn">Book Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 col-xl-3">
            <div class="profile-widget">
              <div class="doc-img">
                <a href="doctor-profile.html">
                  <img
                    class="img-fluid"
                    alt="User Image"
                    src="{% static 'assets/img/doctors/doctor-03.jpg' %}"
                  />
                </a>
                <a href="javascript:void(0)" class="fav-btn">
                  <i class="far fa-bookmark"></i>
                </a>
              </div>
              <div class="pro-content">
                <h3 class="title">
                  <a href="doctor-profile.html">Dr. Deborah Angel</a>
                  <i class="fas fa-check-circle verified"></i>
                </h3>
                <p class="speciality">
                  MBBS, MD - General Medicine, DNB - Cardiology
                </p>
                <div class="rating">
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star"></i>
                  <span class="d-inline-block average-rating">(27)</span>
                </div>
                <ul class="available-info">
                  <li><i class="fas fa-map-marker-alt"></i> Georgia, USA</li>
                  <li><i class="far fa-clock"></i> Available on Fri, 22 Mar</li>
                  <li>
                    <i class="far fa-money-bill-alt"></i> $100 - $400
                    <i
                      class="fas fa-info-circle"
                      data-toggle="tooltip"
                      title="Lorem Ipsum"
                    ></i>
                  </li>
                </ul>
                <div class="row row-sm">
                  <div class="col-6">
                    <a href="doctor-profile.html" class="btn view-btn"
                      >View Profile</a
                    >
                  </div>
                  <div class="col-6">
                    <a href="booking.html" class="btn book-btn">Book Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-6 col-lg-4 col-xl-3">
            <div class="profile-widget">
              <div class="doc-img">
                <a href="doctor-profile.html">
                  <img
                    class="img-fluid"
                    alt="User Image"
                    src="{% static 'assets/img/doctors/doctor-04.jpg' %}"
                  />
                </a>
                <a href="javascript:void(0)" class="fav-btn">
                  <i class="far fa-bookmark"></i>
                </a>
              </div>
              <div class="pro-content">
                <h3 class="title">
                  <a href="doctor-profile.html">Dr. Sofia Brient</a>
                  <i class="fas fa-check-circle verified"></i>
                </h3>
                <p class="speciality">
                  MBBS, MS - General Surgery, MCh - Cardiologist
                </p>
                <div class="rating">
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star filled"></i>
                  <i class="fas fa-star"></i>
                  <span class="d-inline-block average-rating">(4)</span>
                </div>
                <ul class="available-info">
                  <li><i class="fas fa-map-marker-alt"></i> Louisiana, USA</li>
                  <li><i class="far fa-clock"></i> Available on Fri, 22 Mar</li>
                  <li>
                    <i class="far fa-money-bill-alt"></i> $150 - $250
                    <i
                      class="fas fa-info-circle"
                      data-toggle="tooltip"
                      title="Lorem Ipsum"
                    ></i>
                  </li>
                </ul>
                <div class="row row-sm">
                  <div class="col-6">
                    <a href="doctor-profile.html" class="btn view-btn"
                      >View Profile</a
                    >
                  </div>
                  <div class="col-6">
                    <a href="booking.html" class="btn book-btn">Book Now</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Page Content -->

{% endblock content %}

Patient/templates/Patient/info.html
{% extends 'Patient/base.html' %}
{% load static %}


{% block content %}
<!-- Breadcrumb -->
<div class="breadcrumb-bar">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="col-md-12 col-12">
        <nav aria-label="breadcrumb" class="page-breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href="{% url 'doctors:Doctordashboard' %}">Update Profile</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
              Update Profile
            </li>
          </ol>
        </nav>
        <h2 class="breadcrumb-title">Update Profile</h2>
      </div>
    </div>
  </div>
</div>
<!-- /Breadcrumb -->

<!-- Page Content -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5 col-lg-4 col-xl-3 theiaStickySidebar">
        <!-- Profile Sidebar -->
        {% comment %} <div class="profile-sidebar">
          <div class="widget-profile pro-widget-content">
            <div class="profile-info-widget">
              <a href="#" class="booking-doc-img">
                <img
                  src="{% static 'assets/img/doctors/doctor-thumb-02.jpg' %}"
                  alt="User Image"
                />
              </a>
              <div class="profile-det-info">
                <h3>Dr. Fred Ortego</h3>

                <div class="patient-details">
                  <h5 class="mb-0">BDS, MDS - Oral & Maxillofacial Surgery</h5>
                </div>
              </div>
            </div>
          </div>
          <div class="dashboard-widget">
            <nav class="dashboard-menu">
              <ul>
                <li>
                  <a href="{% url 'doctors:Doctordashboard' %}">
                    <i class="fas fa-columns"></i>
                    <span>Dashboard</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'doctors:DoctorAppointments' %}">
                    <i class="fas fa-calendar-check"></i>
                    <span>Appointments</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'doctors:DoctorPatients' %}">
                    <i class="fas fa-user-injured"></i>
                    <span>My Patients</span>
                  </a>
                </li>

                <li class="active">
                  <a href="{% url 'doctors:DoctorProfile' %}">
                    <i class="fas fa-user-cog"></i>
                    <span>Profile Settings</span>
                  </a>
                </li>

                <li>
                  <a href="{% url 'doctors:passwordchange' %}">
                    <i class="fas fa-lock"></i>
                    <span>Change Password</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'accounts:logout' %}">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div> {% endcomment %}
        <!-- /Profile Sidebar -->
      </div>
      <div class="col-md-7 col-lg-8 col-xl-9">
        <!-- Basic Information -->
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Basic Information</h4>
            <div class="row form-row">
              <div class="col-md-12">
                <div class="form-group">
                  <div class="change-avatar">
                    <div class="profile-img">
                      <img
                        src="{% static 'assets/img/profile.png' %}"
                        alt="User Image"
                      />
                    </div>
                    <div class="upload-img">
                      <div class="change-photo-btn">
                        <span><i class="fa fa-upload"></i> Upload Photo</span>
                        {{form.profile_image}}
                      </div>
                      <small class="form-text text-muted"
                        >Allowed JPG, GIF or PNG. Max size of 2MB</small
                      >
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Address <span class="text-danger">*</span></label>
                  {{form.Address}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Mobile <span class="text-danger">*</span></label>
                  {{form.Mobile}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>city <span class="text-danger">*</span></label>
                  {{form.city}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>District <span class="text-danger">*</span></label>
                  {{form.District}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Country</label>
                  {{form.Country}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Gender</label>
                  {{form.Gender}}
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group mb-0">
                  <label>Date of Birth</label>
                  {{form.Date_Of_Birth}}
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Basic Information -->

        <div class="submit-section submit-btn-bottom">
          <button type="submit" class="btn btn-primary submit-btn">
            Save Changes
          </button>
        </div>

        
      </div>
    </div>
  </div>
</div>
<!-- /Page Content -->

{% endblock content %}

Patient/templates/Patient/success.html
{% extends 'Patient/base.html' %}
{% load static %}



{% block content %}
			
			<!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container-fluid">
					<div class="row align-items-center">
						<div class="col-md-12 col-12">
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="{% url 'patient:PatientDashboard' %}">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">Booking</li>
								</ol>
							</nav>
							<h2 class="breadcrumb-title">Booking</h2>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content success-page-cont">
				<div class="container-fluid">
				
					<div class="row justify-content-center">
						<div class="col-lg-6">
						
							<!-- Success Card -->
							<div class="card success-card">
								<div class="card-body">
									<div class="success-cont">
										<i class="fas fa-check"></i>
										<h3>Appointment booked Successfully!</h3>
										<p>Appointment booked with <strong>Dr. Fred Ortego</strong><br> on <strong>12 Nov 2019 5:00PM to 6:00PM</strong></p>
										<a href="invoice-view.html" class="btn btn-primary view-inv-btn">View Invoice</a>
									</div>
								</div>
							</div>
							<!-- /Success Card -->
							
						</div>
					</div>
					
				</div>
			</div>		
			<!-- /Page Content -->
   

{% endblock content %}